import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import Header from '@/components/Header';
import SEOHead from '@/components/SEOHead';
import { Trophy, ArrowLeft, MapPin, Users, Calendar, ChevronRight, Star } from 'lucide-react';
import { cn } from '@/lib/utils';
import Flag from '@/components/Flag';

// ─── Team Data ──────────────────────────────────────────────────────────────

interface WCTeamData {
  name: string;
  code: string;
  flag: string;
  group: string;
  confederation: string;
  fifaRanking: number;
  wcAppearances: number;
  bestFinish: string;
  manager: string;
  playingStyle: string;
  keyPlayers: string[];
  strengths: string[];
  weaknesses: string[];
  groupOpponents: string[];
  overview: string;
  tacticalAnalysis: string;
}

const TEAM_DATA: Record<string, WCTeamData> = {
  ARG: { name: 'Argentina', code: 'ARG', flag: '🇦🇷', group: 'G', confederation: 'CONMEBOL', fifaRanking: 1, wcAppearances: 18, bestFinish: 'Winners (1978, 1986, 2022)', manager: 'Lionel Scaloni', playingStyle: '4-3-3 / 4-4-2', keyPlayers: ['Lionel Messi', 'Julián Álvarez', 'Enzo Fernández'], strengths: ['World-class individual talent', 'Tournament experience', 'Winning mentality'], weaknesses: ['Aging key players', 'Depth in defence'], groupOpponents: ['Colombia', 'Austria', 'Uzbekistan'], overview: 'Argentina enter the 2026 World Cup as defending champions, looking to become the first team since Brazil in 1962 to win consecutive World Cups. Under Lionel Scaloni, La Albiceleste have been the dominant force in world football, winning the 2022 World Cup in Qatar and the 2024 Copa América.', tacticalAnalysis: 'Scaloni\'s Argentina operate in a fluid 4-3-3 system that transitions into a 4-4-2 without the ball. The midfield trio of Enzo Fernández, Rodrigo De Paul, and Alexis Mac Allister provides both defensive solidity and creative impetus. The key tactical question is how much longer Lionel Messi can operate at the highest level in a tournament setting.' },
  BRA: { name: 'Brazil', code: 'BRA', flag: '🇧🇷', group: 'C', confederation: 'CONMEBOL', fifaRanking: 3, wcAppearances: 22, bestFinish: 'Winners (1958, 1962, 1970, 1994, 2002)', manager: 'Dorival Júnior', playingStyle: '4-2-3-1', keyPlayers: ['Vinícius Jr.', 'Rodrygo', 'Endrick'], strengths: ['Attacking firepower', 'Individual brilliance', 'Deep squad'], weaknesses: ['Defensive vulnerabilities', 'Recent tournament disappointments'], groupOpponents: ['Morocco', 'Scotland', 'Haiti'], overview: 'Brazil, the most successful nation in World Cup history with five titles, are desperate to end their trophy drought that stretches back to 2002. The Seleção have a new generation of talent led by Vinícius Jr. and are looking to restore their reputation as the world\'s most entertaining football nation.', tacticalAnalysis: 'Under Dorival Júnior, Brazil play a 4-2-3-1 that allows their attacking talents to express themselves. Vinícius Jr. operating from the left flank is their primary threat, with his pace and dribbling ability making him virtually unplayable on his day. The midfield pivot will be crucial in providing the defensive balance to allow the front four to attack with freedom.' },
  ENG: { name: 'England', code: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', group: 'J', confederation: 'UEFA', fifaRanking: 4, wcAppearances: 16, bestFinish: 'Winners (1966)', manager: 'Thomas Tuchel', playingStyle: '4-3-3', keyPlayers: ['Jude Bellingham', 'Phil Foden', 'Bukayo Saka'], strengths: ['Squad depth', 'Premier League quality', 'Set-piece threat'], weaknesses: ['Tournament knockout pressure', 'Goalkeeping concerns'], groupOpponents: ['Ghana', 'Panama', 'Algeria'], overview: 'England arrive at the 2026 World Cup with perhaps their most talented squad in a generation. Under Thomas Tuchel, the Three Lions are looking to go one step further after reaching the Euro 2024 final. With Jude Bellingham, Phil Foden, and Bukayo Saka in their prime, expectations are sky-high.', tacticalAnalysis: 'Tuchel\'s England deploy a possession-based 4-3-3 with Bellingham as the box-to-box engine. The tactical key is how Tuchel balances the attacking riches at his disposal while maintaining the defensive discipline that got Southgate\'s sides to tournament finals. The full-back positions and how they provide width will be critical.' },
  FRA: { name: 'France', code: 'FRA', flag: '🇫🇷', group: 'I', confederation: 'UEFA', fifaRanking: 2, wcAppearances: 16, bestFinish: 'Winners (1998, 2018)', manager: 'Didier Deschamps', playingStyle: '4-3-3 / 3-4-3', keyPlayers: ['Kylian Mbappé', 'Antoine Griezmann', 'Aurélien Tchouaméni'], strengths: ['World-class forwards', 'Tactical flexibility', 'Tournament pedigree'], weaknesses: ['Squad harmony concerns', 'Aging defensive core'], groupOpponents: ['Senegal', 'Norway', 'Iraq'], overview: 'France are two-time World Cup champions and runners-up in 2022, making them perennial favourites. With Kylian Mbappé leading the line, Les Bleus possess arguably the most feared attack in world football. Deschamps\' experience in managing tournament football gives them a significant edge.', tacticalAnalysis: 'Deschamps oscillates between a 4-3-3 and a 3-4-3 depending on the opponent. The constant is Mbappé\'s freedom to roam and create. Griezmann\'s intelligence in dropping between the lines creates space for Mbappé to attack, while Tchouaméni anchors the midfield. France\'s ability to control games without the ball makes them dangerous in knockout football.' },
  ESP: { name: 'Spain', code: 'ESP', flag: '🇪🇸', group: 'H', confederation: 'UEFA', fifaRanking: 5, wcAppearances: 16, bestFinish: 'Winners (2010)', manager: 'Luis de la Fuente', playingStyle: '4-3-3', keyPlayers: ['Lamine Yamal', 'Pedri', 'Gavi'], strengths: ['Youth and energy', 'Possession dominance', 'Tactical intelligence'], weaknesses: ['Lack of a prolific striker', 'Tournament inexperience of young players'], groupOpponents: ['Saudi Arabia', 'Cape Verde', 'Jordan'], overview: 'Spain are the reigning European champions after their stunning Euro 2024 triumph, built around the most exciting generation of young talent in European football. Lamine Yamal, Pedri, and Gavi form the core of a side that plays some of the most attractive football on the planet.', tacticalAnalysis: 'De la Fuente\'s Spain maintain the nation\'s DNA of possession-based football but with more directness than previous iterations. Lamine Yamal\'s emergence as a world-class winger has added a dimension Spain previously lacked — genuine pace and one-on-one ability on the flanks. The midfield trio of Pedri, Gavi, and Rodri remains the heartbeat of the team.' },
  GER: { name: 'Germany', code: 'GER', flag: '🇩🇪', group: 'E', confederation: 'UEFA', fifaRanking: 8, wcAppearances: 20, bestFinish: 'Winners (1954, 1974, 1990, 2014)', manager: 'Julian Nagelsmann', playingStyle: '4-2-3-1', keyPlayers: ['Florian Wirtz', 'Jamal Musiala', 'Kai Havertz'], strengths: ['Emerging young talent', 'Tactical sophistication', 'Tournament DNA'], weaknesses: ['Recent tournament exits', 'Defensive reliability'], groupOpponents: ['Ivory Coast', 'Curaçao', 'Ecuador'], overview: 'Germany, four-time World Cup champions, are rebuilding under Julian Nagelsmann after disappointing early exits at the 2022 World Cup and Euro 2024 on home soil. The emergence of Florian Wirtz and Jamal Musiala as genuine world-class talents has given German football renewed hope.', tacticalAnalysis: 'Nagelsmann employs a high-pressing 4-2-3-1 that maximizes the creativity of Wirtz and Musiala behind striker Kai Havertz. The tactical innovation lies in how the double pivot protects the back four while allowing the attacking midfielders complete freedom. Germany\'s pressing intensity in the first 20 minutes of matches has been among the highest in European football.' },
  POR: { name: 'Portugal', code: 'POR', flag: '🇵🇹', group: 'K', confederation: 'UEFA', fifaRanking: 6, wcAppearances: 8, bestFinish: 'Third place (1966)', manager: 'Roberto Martínez', playingStyle: '4-3-3', keyPlayers: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Rafael Leão'], strengths: ['Squad depth', 'Individual quality', 'Set-piece threat'], weaknesses: ['Over-reliance on Ronaldo', 'Defensive transitions'], groupOpponents: ['DR Congo', 'Nigeria', 'Switzerland'], overview: 'Portugal enter the 2026 World Cup with Cristiano Ronaldo potentially playing in his final major tournament at age 41. The squad boasts incredible depth with players like Bruno Fernandes, Bernardo Silva, and Rafael Leão providing quality across every position.', tacticalAnalysis: 'Martínez plays a 4-3-3 with Ronaldo as the focal point of the attack. The tactical challenge is accommodating Ronaldo\'s diminishing pressing ability while leveraging his still-elite positioning and finishing. Bruno Fernandes operates as the creative hub, with his passing range connecting defence to attack.' },
  ITA: { name: 'Italy', code: 'ITA', flag: '🇮🇹', group: 'L', confederation: 'UEFA', fifaRanking: 7, wcAppearances: 18, bestFinish: 'Winners (1934, 1938, 1982, 2006)', manager: 'Luciano Spalletti', playingStyle: '3-5-2 / 4-3-3', keyPlayers: ['Nicolò Barella', 'Federico Chiesa', 'Gianluigi Donnarumma'], strengths: ['Tactical discipline', 'Defensive organisation', 'Midfield control'], weaknesses: ['Lack of a world-class striker', 'Recent form inconsistency'], groupOpponents: ['Iran', 'Cameroon', 'Peru'], overview: 'Italy return to the World Cup stage after the humiliation of failing to qualify for the 2022 edition. The Azzurri, four-time world champions, are determined to prove that their absence from Qatar was an aberration rather than a decline.', tacticalAnalysis: 'Spalletti alternates between a 3-5-2 and 4-3-3, with Barella as the driving force in midfield. Italy\'s defensive structure remains their foundation — they are masters of controlling space and forcing opponents into low-percentage chances. The question is whether they have enough attacking quality to break down well-organized defences in knockout rounds.' },
  NED: { name: 'Netherlands', code: 'NED', flag: '🇳🇱', group: 'F', confederation: 'UEFA', fifaRanking: 9, wcAppearances: 11, bestFinish: 'Runners-up (1974, 1978, 2010)', manager: 'Ronald Koeman', playingStyle: '4-3-3 / 3-4-3', keyPlayers: ['Cody Gakpo', 'Xavi Simons', 'Virgil van Dijk'], strengths: ['Total Football philosophy', 'Versatile squad', 'Big-game experience'], weaknesses: ['Lack of a natural goalscorer', 'Defensive vulnerability on the counter'], groupOpponents: ['Japan', 'Sweden', 'Tunisia'], overview: 'The Netherlands, three-time World Cup runners-up, continue their quest for a first title. Under Ronald Koeman, Oranje have rebuilt around a mix of established stars like Virgil van Dijk and exciting young talents like Xavi Simons.', tacticalAnalysis: 'Koeman\'s Netherlands remain faithful to the Total Football philosophy, employing a fluid formation that shifts between 4-3-3 and 3-4-3. The key tactical feature is the positional rotation in midfield, with Xavi Simons given license to drift and create overloads. Van Dijk\'s leadership from the back allows the team to play a high defensive line.' },
  USA: { name: 'USA', code: 'USA', flag: '🇺🇸', group: 'D', confederation: 'CONCACAF', fifaRanking: 14, wcAppearances: 11, bestFinish: 'Third place (1930)', manager: 'Mauricio Pochettino', playingStyle: '4-3-3', keyPlayers: ['Christian Pulisic', 'Weston McKennie', 'Giovanni Reyna'], strengths: ['Home advantage', 'Athletic squad', 'European experience'], weaknesses: ['Pressure of hosting', 'Inconsistent form'], groupOpponents: ['Turkey', 'Paraguay', 'Croatia'], overview: 'The United States co-host the 2026 World Cup and carry the weight of a nation\'s expectations. Under Mauricio Pochettino, the USMNT boast a generation of players competing at Europe\'s biggest clubs. Playing on home soil provides a massive advantage.', tacticalAnalysis: 'Pochettino deploys a high-intensity 4-3-3 that leverages the squad\'s athleticism. Pulisic\'s versatility allows him to operate across the front three, while McKennie provides the engine in midfield. The home crowd factor could prove decisive in tight group-stage matches.' },
  // ─── Group A ──────────────────────────────────────────────────────────────
  MEX: { name: 'Mexico', code: 'MEX', flag: '🇲🇽', group: 'A', confederation: 'CONCACAF', fifaRanking: 15, wcAppearances: 17, bestFinish: 'Quarter-finals (1970, 1986)', manager: 'Javier Aguirre', playingStyle: '4-3-3', keyPlayers: ['Hirving Lozano', 'Edson Álvarez', 'Santiago Giménez'], strengths: ['Passionate home support', 'Tournament experience', 'Technical midfield'], weaknesses: ['Round of 16 barrier', 'Aging squad'], groupOpponents: ['South Korea', 'Czechia', 'South Africa'], overview: 'Mexico co-host the 2026 World Cup and will play the historic opening match at Estadio Azteca. El Tri have reached the Round of 16 in seven consecutive World Cups but have never progressed further in the modern era — a curse they are desperate to break on home soil.', tacticalAnalysis: 'Aguirre favours a compact 4-3-3 that prioritizes defensive solidity before unleashing quick transitions. Edson Álvarez anchors the midfield as the destroyer, while Lozano provides the pace and directness on the flanks. Playing at altitude in Mexico City gives El Tri a significant physiological advantage.' },
  KOR: { name: 'South Korea', code: 'KOR', flag: '🇰🇷', group: 'A', confederation: 'AFC', fifaRanking: 22, wcAppearances: 11, bestFinish: 'Fourth place (2002)', manager: 'Hong Myung-bo', playingStyle: '4-2-3-1', keyPlayers: ['Son Heung-min', 'Lee Kang-in', 'Kim Min-jae'], strengths: ['Work rate and discipline', 'Son Heung-min factor', 'Tactical organization'], weaknesses: ['Creativity beyond Son', 'Physical battles against European sides'], groupOpponents: ['Mexico', 'Czechia', 'South Africa'], overview: 'South Korea carry the legacy of their incredible 2002 semi-final run and boast one of Asia\'s greatest-ever players in Son Heung-min. The Taegeuk Warriors have qualified for every World Cup since 1986 and consistently punch above their weight in tournaments.', tacticalAnalysis: 'South Korea\'s system revolves around Son Heung-min\'s movement and finishing ability. Lee Kang-in provides the creative spark from midfield, while Kim Min-jae marshals the defence. Their pressing intensity and disciplined shape make them difficult to break down, though they can struggle to create against deep-lying defences.' },
  CZE: { name: 'Czechia', code: 'CZE', flag: '🇨🇿', group: 'A', confederation: 'UEFA', fifaRanking: 36, wcAppearances: 2, bestFinish: 'Group stage (2006)', manager: 'Ivan Hašek', playingStyle: '3-5-2', keyPlayers: ['Patrik Schick', 'Tomáš Souček', 'Adam Hložek'], strengths: ['Physical presence', 'Set-piece threat', 'Experienced spine'], weaknesses: ['Lack of pace', 'Limited squad depth'], groupOpponents: ['Mexico', 'South Korea', 'South Africa'], overview: 'Czechia return to the World Cup for the first time since 2006, ending a 20-year absence from football\'s biggest stage. The Czech Republic\'s qualification represents a triumph for their rebuilding project, built around Premier League proven players like Tomáš Souček.', tacticalAnalysis: 'Hašek employs a 3-5-2 system that maximizes Souček\'s box-to-box running and Schick\'s aerial presence. The wing-backs provide width while the three centre-backs offer stability. Czechia\'s set-piece delivery is among the best in European football, making them dangerous from dead-ball situations.' },
  RSA: { name: 'South Africa', code: 'RSA', flag: '🇿🇦', group: 'A', confederation: 'CAF', fifaRanking: 59, wcAppearances: 4, bestFinish: 'Group stage (1998, 2002, 2010)', manager: 'Hugo Broos', playingStyle: '4-3-3', keyPlayers: ['Percy Tau', 'Ronwen Williams', 'Themba Zwane'], strengths: ['Athleticism', 'Counter-attacking speed', 'Goalkeeper quality'], weaknesses: ['Limited international experience', 'Consistency issues'], groupOpponents: ['Mexico', 'South Korea', 'Czechia'], overview: 'South Africa face Mexico in the tournament\'s opening match — a repeat of the 2010 World Cup opener when Bafana Bafana hosted the tournament. The South Africans qualified through a resurgent campaign under Belgian coach Hugo Broos, who has rebuilt the team around youth and athleticism.', tacticalAnalysis: 'Broos has transformed South Africa into a disciplined, counter-attacking unit. Goalkeeper Ronwen Williams is one of Africa\'s best and provides the foundation for a deep defensive block. When they win possession, the pace of their forwards allows them to break at devastating speed.' },
  // ─── Group B ──────────────────────────────────────────────────────────────
  CAN: { name: 'Canada', code: 'CAN', flag: '🇨🇦', group: 'B', confederation: 'CONCACAF', fifaRanking: 40, wcAppearances: 3, bestFinish: 'Group stage (1986, 2022)', manager: 'Jesse Marsch', playingStyle: '4-3-3', keyPlayers: ['Alphonso Davies', 'Jonathan David', 'Tajon Buchanan'], strengths: ['Alphonso Davies pace', 'Strong pressing', 'Home advantage'], weaknesses: ['Defensive frailty', 'Big-game experience'], groupOpponents: ['Australia', 'Bosnia & Herzegovina', 'Qatar'], overview: 'Canada co-host the 2026 World Cup and are looking to make a real impact after their brief 2022 appearance in Qatar where they showed spirit but departed in the group stage. Alphonso Davies remains their standout talent, and the team is built around his explosive pace and attacking ability.', tacticalAnalysis: 'Marsch implements an aggressive pressing system that suits Canada\'s athletic profile. Davies operating as a left winger rather than full-back gives them a genuine match-winner. Jonathan David\'s clinical finishing provides the goals, while the midfield works tirelessly to win possession high up the pitch.' },
  AUS: { name: 'Australia', code: 'AUS', flag: '🇦🇺', group: 'B', confederation: 'AFC', fifaRanking: 24, wcAppearances: 6, bestFinish: 'Round of 16 (2022)', manager: 'Tony Popovic', playingStyle: '4-4-2', keyPlayers: ['Mat Ryan', 'Jackson Irvine', 'Mitchell Duke'], strengths: ['Never-say-die attitude', 'Aerial presence', 'Tournament experience'], weaknesses: ['Technical limitations', 'Aging core'], groupOpponents: ['Canada', 'Bosnia & Herzegovina', 'Qatar'], overview: 'Australia captured hearts at the 2022 World Cup with their spirited run to the Round of 16, defeating Denmark and Tunisia. The Socceroos bring an incredible fighting spirit and a growing football culture that has produced increasingly competitive tournament campaigns.', tacticalAnalysis: 'Australia rely on a solid defensive structure and the ability to compete physically with any opponent. Their 4-4-2 system maximizes their aerial threat from crosses and set pieces. While they may lack the technical finesse of South American or European sides, their organization and determination make them extremely difficult to beat.' },
  BIH: { name: 'Bosnia & Herzegovina', code: 'BIH', flag: '🇧🇦', group: 'B', confederation: 'UEFA', fifaRanking: 55, wcAppearances: 2, bestFinish: 'Group stage (2014)', manager: 'Sergej Barbarez', playingStyle: '4-2-3-1', keyPlayers: ['Edin Džeko', 'Miralem Pjanić', 'Anel Ahmedhodžić'], strengths: ['Experienced spine', 'Attacking creativity', 'Physical presence'], weaknesses: ['Defensive lapses', 'Squad depth'], groupOpponents: ['Canada', 'Australia', 'Qatar'], overview: 'Bosnia & Herzegovina return to the World Cup for only the second time in their history, 12 years after their debut in Brazil. Veterans Edin Džeko and Miralem Pjanić lead a squad that combines Balkan grit with technical sophistication.', tacticalAnalysis: 'Bosnia play an attacking 4-2-3-1 that channels creativity through Pjanić\'s passing range and Džeko\'s movement. The midfield diamond allows them to control possession while Džeko\'s experience and positioning provide the focal point. Their Balkan mentality means they never consider themselves beaten.' },
  QAT: { name: 'Qatar', code: 'QAT', flag: '🇶🇦', group: 'B', confederation: 'AFC', fifaRanking: 35, wcAppearances: 2, bestFinish: 'Group stage (2022)', manager: 'Carlos Queiroz', playingStyle: '5-3-2', keyPlayers: ['Almoez Ali', 'Akram Afif', 'Hassan Al-Haydos'], strengths: ['Asian Cup champions', 'Tactical discipline', 'Home-region preparation'], weaknesses: ['2022 World Cup disappointment', 'Limited European exposure'], groupOpponents: ['Canada', 'Australia', 'Bosnia & Herzegovina'], overview: 'Qatar look to redeem themselves after a disappointing 2022 World Cup on home soil where they lost all three group matches. As 2023 Asian Cup champions, they proved they can compete at the highest level in Asian football and will bring improved experience to 2026.', tacticalAnalysis: 'Under Queiroz, Qatar have adopted a more defensive approach with a 5-3-2 that prioritizes compactness. Akram Afif\'s creativity and Almoez Ali\'s finishing remain their biggest attacking threats. The key tactical challenge is maintaining concentration for 90 minutes against teams with greater individual quality.' },
  // ─── Group C ──────────────────────────────────────────────────────────────
  MAR: { name: 'Morocco', code: 'MAR', flag: '🇲🇦', group: 'C', confederation: 'CAF', fifaRanking: 13, wcAppearances: 7, bestFinish: 'Semi-finals (2022)', manager: 'Walid Regragui', playingStyle: '4-3-3', keyPlayers: ['Achraf Hakimi', 'Hakim Ziyech', 'Youssef En-Nesyri'], strengths: ['Defensive resilience', 'Counter-attacking threat', 'Team unity'], weaknesses: ['Maintaining 2022 standards', 'Goalscoring consistency'], groupOpponents: ['Brazil', 'Scotland', 'Haiti'], overview: 'Morocco were the sensation of the 2022 World Cup, becoming the first African and Arab nation to reach a semi-final. The Atlas Lions defeated Belgium, Spain, and Portugal on their way to a historic fourth-place finish that captivated the football world.', tacticalAnalysis: 'Regragui\'s Morocco are built on an extraordinary defensive foundation. Hakimi provides explosive attacking thrust from right-back, while the centre-back pairing is among the most organized in world football. Their ability to absorb pressure and strike on the counter makes them a nightmare for possession-dominant sides.' },
  SCO: { name: 'Scotland', code: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', group: 'C', confederation: 'UEFA', fifaRanking: 42, wcAppearances: 9, bestFinish: 'Group stage', manager: 'Steve Clarke', playingStyle: '3-5-2', keyPlayers: ['John McGinn', 'Scott McTominay', 'Andy Robertson'], strengths: ['Warrior mentality', 'Set-piece prowess', 'Organized defence'], weaknesses: ['Lack of goalscoring options', 'Quality in depth'], groupOpponents: ['Brazil', 'Morocco', 'Haiti'], overview: 'Scotland return to the World Cup for the first time since 1998, ending a 28-year absence. Under Steve Clarke, the Tartan Army have become one of Europe\'s most improved sides, qualifying ahead of several higher-ranked nations.', tacticalAnalysis: 'Clarke\'s 3-5-2 maximizes Scotland\'s strengths — aerial dominance, midfield energy, and the quality of Robertson at wing-back. McTominay\'s late runs into the box have become a significant goalscoring weapon, while McGinn\'s driving runs provide momentum in transition.' },
  HAI: { name: 'Haiti', code: 'HAI', flag: '🇭🇹', group: 'C', confederation: 'CONCACAF', fifaRanking: 82, wcAppearances: 2, bestFinish: 'Group stage (1974)', manager: 'Antoine Kombouaré', playingStyle: '4-4-2', keyPlayers: ['Frantzdy Pierrot', 'Derrick Etienne Jr.', 'Steeven Saba'], strengths: ['Passionate support', 'Physical athleticism', 'Nothing to lose'], weaknesses: ['Quality gap to top nations', 'Limited preparation resources'], groupOpponents: ['Brazil', 'Morocco', 'Scotland'], overview: 'Haiti\'s qualification for the 2026 World Cup is one of the great stories of CONCACAF football. Returning to the World Cup for the first time since 1974, this Caribbean nation carries the hopes and dreams of 11 million people. They face a tough group but will be determined to make their mark.', tacticalAnalysis: 'Haiti rely on a disciplined 4-4-2 that stays compact and uses the pace of their forwards on the counter-attack. Their qualification campaign showed they can defend resolutely and take their chances when they come. Against Brazil and Morocco, they will need to produce the performances of their lives.' },
  // ─── Group D ──────────────────────────────────────────────────────────────
  TUR: { name: 'Turkey', code: 'TUR', flag: '🇹🇷', group: 'D', confederation: 'UEFA', fifaRanking: 26, wcAppearances: 3, bestFinish: 'Third place (2002)', manager: 'Vincenzo Montella', playingStyle: '4-2-3-1', keyPlayers: ['Hakan Çalhanoğlu', 'Arda Güler', 'Kenan Yıldız'], strengths: ['Exciting young talent', 'Passionate fan base', 'Tactical flexibility'], weaknesses: ['Inconsistency', 'Defensive errors'], groupOpponents: ['USA', 'Paraguay', 'Croatia'], overview: 'Turkey boast one of the most exciting young generations in European football, led by Real Madrid\'s Arda Güler and Juventus\' Kenan Yıldız. Their run to the Euro 2024 quarter-finals showed they can compete with anyone on their day, and they carry the legacy of their magical 2002 World Cup campaign.', tacticalAnalysis: 'Montella has built Turkey\'s system around the creative brilliance of Güler and the midfield control of Çalhanoğlu. The 4-2-3-1 gives Güler freedom to roam behind the striker, while Çalhanoğlu dictates tempo from deep. When Turkey click, they play some of the most attractive football in European football.' },
  PAR: { name: 'Paraguay', code: 'PAR', flag: '🇵🇾', group: 'D', confederation: 'CONMEBOL', fifaRanking: 50, wcAppearances: 9, bestFinish: 'Quarter-finals (2010)', manager: 'Alfaro', playingStyle: '4-4-2', keyPlayers: ['Miguel Almirón', 'Julio Enciso', 'Gustavo Gómez'], strengths: ['South American grit', 'Defensive organization', 'Set-piece threat'], weaknesses: ['Ageing squad', 'Limited attacking creativity'], groupOpponents: ['USA', 'Turkey', 'Croatia'], overview: 'Paraguay return to the World Cup after missing the 2022 edition. La Albirroja are known for their fighting spirit and ability to grind out results against technically superior opponents. Their 2010 quarter-final run under Gerardo Martino remains a benchmark for Paraguayan football.', tacticalAnalysis: 'Paraguay play a typically South American 4-4-2 that prioritizes defensive solidity and quick transitions. Almirón provides pace and directness from the wing, while the midfield battle is where Paraguay thrive. They are masters of the dark arts — time-wasting, tactical fouling, and physical intimidation.' },
  CRO: { name: 'Croatia', code: 'CRO', flag: '🇭🇷', group: 'D', confederation: 'UEFA', fifaRanking: 10, wcAppearances: 7, bestFinish: 'Runners-up (2018)', manager: 'Zlatko Dalić', playingStyle: '4-3-3', keyPlayers: ['Luka Modrić', 'Joško Gvardiol', 'Mateo Kovačić'], strengths: ['Midfield mastery', 'Tournament pedigree', 'Big-game mentality'], weaknesses: ['Aging Modrić', 'Goalscoring dependency'], groupOpponents: ['USA', 'Turkey', 'Paraguay'], overview: 'Croatia are serial overachievers — World Cup finalists in 2018 and third place in 2022 for a nation of just four million people. The question for 2026 is whether the legendary Luka Modrić can defy time once more or whether the next generation, led by Gvardiol, can carry the torch.', tacticalAnalysis: 'Croatia\'s football identity is defined by midfield control. Even as Modrić approaches his 41st birthday, the system revolves around possession and patience in midfield. Gvardiol\'s emergence as a world-class centre-back adds a new dimension, while Kovačić provides the energy that Modrić can no longer sustain for 90 minutes.' },
  // ─── Group E ──────────────────────────────────────────────────────────────
  CIV: { name: 'Ivory Coast', code: 'CIV', flag: '🇨🇮', group: 'E', confederation: 'CAF', fifaRanking: 38, wcAppearances: 4, bestFinish: 'Group stage', manager: 'Emerse Faé', playingStyle: '4-3-3', keyPlayers: ['Sébastien Haller', 'Franck Kessié', 'Simon Adingra'], strengths: ['2024 AFCON champions', 'Physical power', 'Counter-attacking pace'], weaknesses: ['Consistency issues', 'Tactical naivety'], groupOpponents: ['Germany', 'Curaçao', 'Ecuador'], overview: 'Ivory Coast are the reigning Africa Cup of Nations champions after their dramatic triumph on home soil in 2024. The Elephants have a proud World Cup history featuring the golden generation of Drogba, Touré, and Gervinho, and are looking to finally translate African success into World Cup progress.', tacticalAnalysis: 'Faé\'s Ivory Coast blend physical power with technical quality. Kessié provides the midfield muscle, while Haller\'s hold-up play allows the pacy wingers to exploit space behind opposing full-backs. Their AFCON triumph gave them the belief that they can compete with anyone in a tournament setting.' },
  CUW: { name: 'Curaçao', code: 'CUW', flag: '🇨🇼', group: 'E', confederation: 'CONCACAF', fifaRanking: 93, wcAppearances: 1, bestFinish: 'Debut', manager: 'Dick Advocaat', playingStyle: '5-4-1', keyPlayers: ['Cuco Martina', 'Leandro Bacuna', 'Rangelo Janga'], strengths: ['Caribbean flair', 'Dutch football heritage', 'Underdog mentality'], weaknesses: ['Small player pool', 'Lack of top-level experience', 'Physical limitations'], groupOpponents: ['Germany', 'Ivory Coast', 'Ecuador'], overview: 'Curaçao\'s qualification for the 2026 World Cup is the greatest achievement in their sporting history. This tiny Caribbean island of 150,000 people has produced a team capable of competing on the world stage, drawing on players from the Dutch football system.', tacticalAnalysis: 'Under the experienced Advocaat, Curaçao will likely adopt a deep defensive block with a 5-4-1 to limit the damage against Germany and Ivory Coast. Many of their players have Dutch league experience, bringing tactical discipline. Their qualification was built on resilience and team spirit rather than individual brilliance.' },
  ECU: { name: 'Ecuador', code: 'ECU', flag: '🇪🇨', group: 'E', confederation: 'CONMEBOL', fifaRanking: 30, wcAppearances: 4, bestFinish: 'Round of 16 (2006)', manager: 'Sebastián Beccacece', playingStyle: '4-3-3', keyPlayers: ['Moisés Caicedo', 'Piero Hincapié', 'Kendry Páez'], strengths: ['Young and dynamic squad', 'Altitude advantage in qualifiers', 'Physical intensity'], weaknesses: ['Away form', 'Tournament inexperience of young core'], groupOpponents: ['Germany', 'Ivory Coast', 'Curaçao'], overview: 'Ecuador have established themselves as a consistent CONMEBOL qualifier with a squad that blends youth and energy. Moisés Caicedo has emerged as one of the world\'s most coveted midfielders, while teenage sensation Kendry Páez represents the next wave of Ecuadorian talent.', tacticalAnalysis: 'Ecuador play an aggressive, high-energy 4-3-3 built around Caicedo\'s extraordinary engine and passing range. Their youth means they can press relentlessly for 90 minutes, but it also means they can be tactically naive in big moments. Hincapié\'s composure at centre-back provides the defensive foundation.' },
  // ─── Group F ──────────────────────────────────────────────────────────────
  JPN: { name: 'Japan', code: 'JPN', flag: '🇯🇵', group: 'F', confederation: 'AFC', fifaRanking: 18, wcAppearances: 7, bestFinish: 'Round of 16 (2002, 2018, 2022)', manager: 'Hajime Moriyasu', playingStyle: '4-2-3-1', keyPlayers: ['Takefusa Kubo', 'Ritsu Doan', 'Wataru Endo'], strengths: ['Technical excellence', 'Pressing intensity', 'Giant-killing ability'], weaknesses: ['Closing out big games', 'Physicality'], groupOpponents: ['Netherlands', 'Sweden', 'Tunisia'], overview: 'Japan stunned the world in 2022 by defeating both Germany and Spain in the group stage, establishing themselves as genuine contenders. The Samurai Blue have one of the most technically gifted squads in Asian football history, with players competing at the highest levels of European football.', tacticalAnalysis: 'Moriyasu\'s Japan play a sophisticated pressing game that can suffocate even the best passing teams — as Germany and Spain discovered in 2022. Kubo provides the creative spark, while Endo anchors the midfield with his reading of the game. Japan\'s ability to switch between a high press and a deep block within the same match makes them tactically unpredictable.' },
  SWE: { name: 'Sweden', code: 'SWE', flag: '🇸🇪', group: 'F', confederation: 'UEFA', fifaRanking: 20, wcAppearances: 12, bestFinish: 'Runners-up (1958)', manager: 'Jon Dahl Tomasson', playingStyle: '4-4-2', keyPlayers: ['Alexander Isak', 'Dejan Kulusevski', 'Viktor Gyökeres'], strengths: ['Premier League firepower', 'Physical presence', 'Nordic mentality'], weaknesses: ['Post-Ibrahimović transition', 'Midfield creativity'], groupOpponents: ['Netherlands', 'Japan', 'Tunisia'], overview: 'Sweden have entered a new era after the retirement of Zlatan Ibrahimović, with Alexander Isak and Viktor Gyökeres leading a new generation. Gyökeres\' prolific scoring at Sporting CP has made him one of Europe\'s most sought-after strikers, while Isak has established himself as one of the Premier League\'s best.', tacticalAnalysis: 'Tomasson deploys a direct 4-4-2 that leverages the physicality and finishing ability of Isak and Gyökeres. Kulusevski provides the creative link between midfield and attack. Sweden\'s direct style means they don\'t need to dominate possession — they are happy to cede the ball and strike on the counter with devastating efficiency.' },
  TUN: { name: 'Tunisia', code: 'TUN', flag: '🇹🇳', group: 'F', confederation: 'CAF', fifaRanking: 44, wcAppearances: 6, bestFinish: 'Group stage', manager: 'Faouzi Benzarti', playingStyle: '4-3-3', keyPlayers: ['Aïssa Laïdouni', 'Mohamed Ali Ben Romdhane', 'Seifeddine Jaziri'], strengths: ['Defensive discipline', 'North African passion', 'Big-game experience'], weaknesses: ['Goalscoring', 'Limited squad depth'], groupOpponents: ['Netherlands', 'Japan', 'Sweden'], overview: 'Tunisia are perennial African qualifiers with six World Cup appearances. The Eagles of Carthage memorably held Denmark to a draw and defeated France in the 2022 group stage, showing they can compete with European powerhouses on their day.', tacticalAnalysis: 'Tunisia play a disciplined 4-3-3 that prioritizes not conceding. Their midfield trio works tirelessly to close down space and force turnovers. When they win the ball, the transition is quick and direct. Tunisia\'s biggest challenge has always been scoring enough goals to convert good defensive performances into tournament progress.' },
  // ─── Group G ──────────────────────────────────────────────────────────────
  COL: { name: 'Colombia', code: 'COL', flag: '🇨🇴', group: 'G', confederation: 'CONMEBOL', fifaRanking: 12, wcAppearances: 7, bestFinish: 'Quarter-finals (2014)', manager: 'Néstor Lorenzo', playingStyle: '4-3-3', keyPlayers: ['Luis Díaz', 'James Rodríguez', 'Jhon Arias'], strengths: ['Attacking flair', 'Copa América runners-up', 'Creative midfield'], weaknesses: ['Defensive vulnerability', 'Inconsistent qualifying form'], groupOpponents: ['Argentina', 'Austria', 'Uzbekistan'], overview: 'Colombia were 2024 Copa América runners-up, losing to Argentina in the final. Los Cafeteros possess one of South America\'s most exciting attacks led by Liverpool\'s Luis Díaz, while the evergreen James Rodríguez continues to produce magic in a Colombian shirt at age 34.', tacticalAnalysis: 'Lorenzo\'s Colombia play an expansive 4-3-3 that gives their creative players licence to express themselves. Díaz terrorizes defences with his pace from the left, while James orchestrates from a free role. Colombia\'s attacking output is among the highest in CONMEBOL qualifying, though they can be vulnerable when opponents press them high.' },
  AUT: { name: 'Austria', code: 'AUT', flag: '🇦🇹', group: 'G', confederation: 'UEFA', fifaRanking: 25, wcAppearances: 8, bestFinish: 'Third place (1954)', manager: 'Ralf Rangnick', playingStyle: '4-4-2 pressing', keyPlayers: ['David Alaba', 'Christoph Baumgartner', 'Marcel Sabitzer'], strengths: ['Gegenpressing pioneers', 'Tactical discipline', 'Team cohesion'], weaknesses: ['Alaba injury concerns', 'Lack of star power'], groupOpponents: ['Argentina', 'Colombia', 'Uzbekistan'], overview: 'Austria under Ralf Rangnick have become one of Europe\'s most improved teams, playing an intense pressing game that has troubled every opponent they\'ve faced. Their Euro 2024 campaign, where they topped a group containing France, proved they are no longer a footballing minnow.', tacticalAnalysis: 'Rangnick\'s Austria are the purest expression of gegenpressing in international football. They press with extraordinary intensity for 90 minutes, winning the ball high and attacking immediately. Sabitzer provides the goals from midfield, while Baumgartner\'s movement between the lines creates chaos for opposing defences. This is arguably the best-coached team at the tournament.' },
  UZB: { name: 'Uzbekistan', code: 'UZB', flag: '🇺🇿', group: 'G', confederation: 'AFC', fifaRanking: 62, wcAppearances: 1, bestFinish: 'Debut', manager: 'Srecko Katanec', playingStyle: '4-2-3-1', keyPlayers: ['Eldor Shomurodov', 'Jaloliddin Masharipov', 'Oston Urunov'], strengths: ['Passionate support', 'Physical presence', 'Nothing to lose mentality'], weaknesses: ['World Cup debut nerves', 'Quality gap to top nations'], groupOpponents: ['Argentina', 'Colombia', 'Austria'], overview: 'Uzbekistan qualify for their first-ever FIFA World Cup, crowning years of investment in football development. The White Wolves have been one of Asia\'s strongest non-qualifying nations for decades, repeatedly coming close before finally breaking through for 2026.', tacticalAnalysis: 'Uzbekistan play a structured 4-2-3-1 that balances defensive responsibility with attacking ambition. Shomurodov leads the line with experience from Serie A, providing a focal point. Their debut will be against the world\'s best, but the freedom of zero expectations could prove liberating.' },
  // ─── Group H ──────────────────────────────────────────────────────────────
  KSA: { name: 'Saudi Arabia', code: 'KSA', flag: '🇸🇦', group: 'H', confederation: 'AFC', fifaRanking: 56, wcAppearances: 7, bestFinish: 'Round of 16 (1994)', manager: 'Roberto Mancini', playingStyle: '4-3-3', keyPlayers: ['Salem Al-Dawsari', 'Firas Al-Buraikan', 'Mohamed Kanno'], strengths: ['2022 Argentina victory legacy', 'Home-region investment', 'Team spirit'], weaknesses: ['Domestic league quality questions', 'Consistency'], groupOpponents: ['Spain', 'Cape Verde', 'Jordan'], overview: 'Saudi Arabia produced the greatest shock in World Cup history by defeating Argentina in the 2022 group stage. The Green Falcons carry that memory as proof they can beat anyone. Massive investment in the Saudi Pro League has raised the profile of Saudi football globally.', tacticalAnalysis: 'Under Mancini, Saudi Arabia play a more European-influenced 4-3-3 with emphasis on structured build-up play. Al-Dawsari remains the creative spark, while the pressing intensity that shocked Argentina has become a permanent feature. The tactical challenge is maintaining that level of performance against Spain.' },
  CPV: { name: 'Cape Verde', code: 'CPV', flag: '🇨🇻', group: 'H', confederation: 'CAF', fifaRanking: 72, wcAppearances: 1, bestFinish: 'Debut', manager: 'Bubista', playingStyle: '4-4-2', keyPlayers: ['Ryan Mendes', 'Garry Rodrigues', 'Kenny Rocha'], strengths: ['Island mentality', 'Portuguese football diaspora', 'Defensive resilience'], weaknesses: ['Population of 600,000', 'Debut pressure', 'Physical demands of tournament football'], groupOpponents: ['Spain', 'Saudi Arabia', 'Jordan'], overview: 'Cape Verde\'s World Cup qualification is one of the most remarkable stories in football history. An island nation of just 600,000 people — smaller than most individual cities hosting the tournament — has qualified for football\'s biggest stage for the first time.', tacticalAnalysis: 'Cape Verde draw on a diaspora of players based primarily in Portuguese football, giving them a tactical sophistication that belies their size. Their 4-4-2 prioritizes defensive compactness and counter-attacking speed. Every match at the World Cup will be a celebration for this tiny nation, regardless of the result.' },
  JOR: { name: 'Jordan', code: 'JOR', flag: '🇯🇴', group: 'H', confederation: 'AFC', fifaRanking: 70, wcAppearances: 1, bestFinish: 'Debut', manager: 'Hussein Ammouta', playingStyle: '4-2-3-1', keyPlayers: ['Mousa Al-Taamari', 'Yazan Al-Naimat', 'Baha\' Faisal'], strengths: ['2024 Asian Cup runners-up', 'Organized defence', 'Set-piece threat'], weaknesses: ['World Cup debut', 'Physical limitations against top sides'], groupOpponents: ['Spain', 'Saudi Arabia', 'Cape Verde'], overview: 'Jordan arrive at the 2026 World Cup on the back of a stunning run to the 2024 Asian Cup Final, where they pushed Qatar all the way. This unexpected rise has transformed Jordanian football, with the national team becoming a source of immense pride for the nation.', tacticalAnalysis: 'Jordan play a compact 4-2-3-1 that is extremely difficult to break down. Their defensive organization was the foundation of their Asian Cup run, where they conceded remarkably few goals. Al-Taamari provides flair and creativity, while the team\'s collective spirit makes them greater than the sum of their parts.' },
  // ─── Group I ──────────────────────────────────────────────────────────────
  SEN: { name: 'Senegal', code: 'SEN', flag: '🇸🇳', group: 'I', confederation: 'CAF', fifaRanking: 17, wcAppearances: 3, bestFinish: 'Quarter-finals (2002)', manager: 'Aliou Cissé', playingStyle: '4-3-3', keyPlayers: ['Sadio Mané', 'Kalidou Koulibaly', 'Ismaïla Sarr'], strengths: ['Physical dominance', 'AFCON winners (2022)', 'Individual quality'], weaknesses: ['Post-Mané transition', 'Consistency in qualifying'], groupOpponents: ['France', 'Norway', 'Iraq'], overview: 'Senegal are the 2022 Africa Cup of Nations champions and one of the strongest teams on the African continent. The Lions of Teranga reached the 2002 World Cup quarter-finals in one of the tournament\'s greatest debut performances, and they carry that spirit into every campaign.', tacticalAnalysis: 'Cissé\'s Senegal combine physical power with technical quality in a 4-3-3 that can match any team athletically. Koulibaly provides a granite wall at centre-back, while the attacking options of Mané and Sarr give them pace and unpredictability. Senegal\'s biggest asset is their collective mentality.' },
  NOR: { name: 'Norway', code: 'NOR', flag: '🇳🇴', group: 'I', confederation: 'UEFA', fifaRanking: 48, wcAppearances: 4, bestFinish: 'Round of 16 (1998)', manager: 'Ståle Solbakken', playingStyle: '4-3-3', keyPlayers: ['Erling Haaland', 'Martin Ødegaard', 'Sander Berge'], strengths: ['Haaland and Ødegaard', 'Nordic physicality', 'Premier League core'], weaknesses: ['Over-reliance on two players', 'Squad depth'], groupOpponents: ['France', 'Senegal', 'Iraq'], overview: 'Norway\'s qualification is built on two generational talents — Erling Haaland and Martin Ødegaard. For the first time in decades, Norway have a squad capable of competing at the World Cup, with Haaland\'s goalscoring record making them a threat to anyone in a single match.', tacticalAnalysis: 'Everything in Norway\'s system is designed to get the ball to Haaland in dangerous positions. Ødegaard\'s creativity from midfield provides the ammunition, while Haaland\'s movement and finishing does the rest. The challenge is what happens when opponents successfully neutralize this partnership — Norway\'s Plan B remains a work in progress.' },
  IRQ: { name: 'Iraq', code: 'IRQ', flag: '🇮🇶', group: 'I', confederation: 'AFC', fifaRanking: 63, wcAppearances: 2, bestFinish: 'Group stage (1986)', manager: 'Jorge Luis Pinto', playingStyle: '4-2-3-1', keyPlayers: ['Mohanad Ali', 'Ibrahim Bayesh', 'Ali Adnan'], strengths: ['National pride', 'Improving youth system', 'Physical resilience'], weaknesses: ['Infrastructure challenges', 'World Cup inexperience'], groupOpponents: ['France', 'Senegal', 'Norway'], overview: 'Iraq return to the World Cup for only the second time, 40 years after their 1986 debut. This qualification represents a triumph over incredible adversity — Iraqi football has survived wars, sanctions, and instability to produce a team capable of competing on the world stage.', tacticalAnalysis: 'Under Pinto, Iraq play a structured 4-2-3-1 that maximizes their physical attributes. Mohanad Ali\'s pace provides the primary attacking outlet, while the midfield pair works tirelessly to disrupt opponents. Iraq\'s greatest weapon is the emotion and passion they bring — for a nation that has endured so much, every World Cup match is a celebration of resilience.' },
  // ─── Group J ──────────────────────────────────────────────────────────────
  GHA: { name: 'Ghana', code: 'GHA', flag: '🇬🇭', group: 'J', confederation: 'CAF', fifaRanking: 46, wcAppearances: 4, bestFinish: 'Quarter-finals (2010)', manager: 'Otto Addo', playingStyle: '4-2-3-1', keyPlayers: ['Mohammed Kudus', 'Thomas Partey', 'Inaki Williams'], strengths: ['Individual brilliance', 'West African flair', 'Big-game pedigree'], weaknesses: ['Organizational issues', 'Defensive fragility'], groupOpponents: ['England', 'Panama', 'Algeria'], overview: 'Ghana were agonizingly close to becoming the first African team to reach a World Cup semi-final in 2010, denied only by Luis Suárez\'s infamous handball. The Black Stars have produced generations of world-class talent and Mohammed Kudus represents the latest in that proud tradition.', tacticalAnalysis: 'Ghana\'s attacking philosophy centres on Kudus\'s extraordinary ability to beat players and create chances from nothing. Partey provides the midfield platform, while Williams\'s physical presence stretches defences. Ghana are most dangerous when they play with freedom and expression.' },
  PAN: { name: 'Panama', code: 'PAN', flag: '🇵🇦', group: 'J', confederation: 'CONCACAF', fifaRanking: 58, wcAppearances: 2, bestFinish: 'Group stage (2018)', manager: 'Thomas Christiansen', playingStyle: '5-3-2', keyPlayers: ['Eric Davis', 'Adalberto Carrasquilla', 'José Fajardo'], strengths: ['Defensive resilience', 'CONCACAF experience', 'Physical presence'], weaknesses: ['Limited attacking quality', 'Ageing core players'], groupOpponents: ['England', 'Ghana', 'Algeria'], overview: 'Panama qualified for their second World Cup after their emotional debut in 2018, where the entire nation celebrated scoring their first-ever World Cup goal against England. The Canaleros are built on defensive discipline and the fighting spirit that defines Central American football.', tacticalAnalysis: 'Christiansen employs a 5-3-2 that prioritizes defensive numbers and compactness. Panama accept they will have less possession against stronger teams and instead focus on being difficult to break down. Set pieces and transitions provide their best opportunities to score.' },
  ALG: { name: 'Algeria', code: 'ALG', flag: '🇩🇿', group: 'J', confederation: 'CAF', fifaRanking: 32, wcAppearances: 5, bestFinish: 'Round of 16 (2014)', manager: 'Vladimir Petković', playingStyle: '4-3-3', keyPlayers: ['Riyad Mahrez', 'Ismaël Bennacer', 'Aïmen Moueffek'], strengths: ['2019 AFCON champions legacy', 'Technical midfield', 'North African intensity'], weaknesses: ['Post-Mahrez transition concerns', 'Qualifying inconsistency'], groupOpponents: ['England', 'Ghana', 'Panama'], overview: 'Algeria are the 2019 Africa Cup of Nations champions and carry the proud tradition of North African football. The Desert Foxes\' run to the 2014 Round of 16 — where they pushed Germany to extra time — showed they can compete at the highest level.', tacticalAnalysis: 'Algeria play a fluid 4-3-3 that relies on Bennacer\'s midfield control and quick transitions through the flanks. Mahrez\'s experience at the top level provides the creative spark, while the younger generation brings energy and pressing intensity. Algeria\'s biggest challenge is maintaining the standards set by their golden generation.' },
  // ─── Group K ──────────────────────────────────────────────────────────────
  COD: { name: 'DR Congo', code: 'COD', flag: '🇨🇩', group: 'K', confederation: 'CAF', fifaRanking: 52, wcAppearances: 2, bestFinish: 'Group stage (1974)', manager: 'Sébastien Desabre', playingStyle: '4-3-3', keyPlayers: ['Chancel Mbemba', 'Cédric Bakambu', 'Yoane Wissa'], strengths: ['Physical power', 'Explosive attacking pace', 'Improving rapidly'], weaknesses: ['Defensive lapses', 'Tournament inexperience'], groupOpponents: ['Portugal', 'Nigeria', 'Switzerland'], overview: 'The Democratic Republic of Congo return to the World Cup for the first time since 1974 when they played as Zaire. The Leopards\' qualification represents one of African football\'s great comeback stories, powered by a diaspora of players competing in Europe\'s top leagues.', tacticalAnalysis: 'DR Congo play an exciting, attack-minded 4-3-3 that utilizes the physical attributes of their players. Mbemba provides experience at the back, while the forward line combines pace with power. Their qualification campaign showed they can beat anyone on their day.' },
  NGA: { name: 'Nigeria', code: 'NGA', flag: '🇳🇬', group: 'K', confederation: 'CAF', fifaRanking: 28, wcAppearances: 7, bestFinish: 'Round of 16 (1994, 1998, 2014)', manager: 'Finidi George', playingStyle: '4-3-3', keyPlayers: ['Victor Osimhen', 'Samuel Chukwueze', 'Alex Iwobi'], strengths: ['Osimhen factor', 'Pace and power', 'Deep talent pool'], weaknesses: ['Organizational issues', 'Consistency'], groupOpponents: ['Portugal', 'DR Congo', 'Switzerland'], overview: 'Nigeria are Africa\'s most consistent World Cup performers with seven appearances and three Round of 16 campaigns. The Super Eagles\' attacking talent, led by Victor Osimhen, makes them one of the most exciting teams at the tournament. Osimhen\'s goalscoring record puts him among the world\'s best strikers.', tacticalAnalysis: 'Nigeria\'s system is built to supply Osimhen with chances. Chukwueze provides pace and trickery from the right, while Iwobi links play from midfield. When Osimhen is firing, Nigeria can beat anyone. The challenge is maintaining defensive discipline when opponents commit numbers forward to suppress their attacking threat.' },
  SUI: { name: 'Switzerland', code: 'SUI', flag: '🇨🇭', group: 'K', confederation: 'UEFA', fifaRanking: 16, wcAppearances: 12, bestFinish: 'Quarter-finals (1934, 1938, 1954, 2024)', manager: 'Murat Yakın', playingStyle: '3-4-3', keyPlayers: ['Granit Xhaka', 'Ruben Vargas', 'Breel Embolo'], strengths: ['Tactical organization', 'Multicultural squad', 'Euro 2024 quarter-finalists'], weaknesses: ['Lack of a prolific striker', 'Goalkeeper transition post-Sommer'], groupOpponents: ['Portugal', 'DR Congo', 'Nigeria'], overview: 'Switzerland have become one of European football\'s most reliable performers, reaching the knockout stages at virtually every major tournament. Their multicultural squad, drawing on talent with roots across Europe, Africa, and the Balkans, gives them a unique blend of styles and perspectives.', tacticalAnalysis: 'Yakın\'s 3-4-3 is perfectly suited to Switzerland\'s personnel. Xhaka dictates the tempo from midfield, while the wing-backs provide width and attacking thrust. The three-man defence gives them numerical superiority at the back, allowing the midfield to push forward. Switzerland rarely lose by big margins and always compete.' },
  // ─── Group L ──────────────────────────────────────────────────────────────
  IRN: { name: 'Iran', code: 'IRN', flag: '🇮🇷', group: 'L', confederation: 'AFC', fifaRanking: 19, wcAppearances: 6, bestFinish: 'Group stage', manager: 'Amir Ghalenoei', playingStyle: '4-1-4-1', keyPlayers: ['Mehdi Taremi', 'Sardar Azmoun', 'Alireza Jahanbakhsh'], strengths: ['Asian powerhouse', 'Defensive discipline', 'Experienced core'], weaknesses: ['Knockout-round barrier', 'Political distractions'], groupOpponents: ['Italy', 'Cameroon', 'Peru'], overview: 'Iran are Asia\'s most consistent World Cup qualifiers and have come agonizingly close to reaching the knockout stages on multiple occasions. Team Melli pushed Portugal and Spain to the wire in previous tournaments and are determined to finally break through the group-stage barrier.', tacticalAnalysis: 'Iran play a disciplined 4-1-4-1 that is designed to frustrate and contain. Taremi provides world-class quality up front with his hold-up play and finishing, while Azmoun offers pace in behind. Iran\'s defensive organization has troubled every major team they\'ve faced, and they will make Group L extremely competitive.' },
  CMR: { name: 'Cameroon', code: 'CMR', flag: '🇨🇲', group: 'L', confederation: 'CAF', fifaRanking: 43, wcAppearances: 8, bestFinish: 'Quarter-finals (1990)', manager: 'Marc Brys', playingStyle: '4-3-3', keyPlayers: ['André-Frank Zambo Anguissa', 'Vincent Aboubakar', 'Bryan Mbeumo'], strengths: ['Physical dominance', 'Individual quality', 'Tournament heritage'], weaknesses: ['Organizational issues', 'Inconsistency'], groupOpponents: ['Italy', 'Iran', 'Peru'], overview: 'Cameroon are the most successful Central African nation in World Cup history, with their iconic 1990 run under Roger Milla capturing the world\'s imagination. The Indomitable Lions carry that legacy and remain one of Africa\'s most talented and entertaining teams.', tacticalAnalysis: 'Cameroon\'s 4-3-3 is built around the midfield excellence of Zambo Anguissa, who provides both defensive coverage and progressive carrying. Mbeumo\'s emergence as a Premier League star adds a new dimension to their attack. Cameroon\'s physical presence and pace make them a handful for any defence.' },
  PER: { name: 'Peru', code: 'PER', flag: '🇵🇪', group: 'L', confederation: 'CONMEBOL', fifaRanking: 33, wcAppearances: 6, bestFinish: 'Quarter-finals (1970, 1978)', manager: 'Jorge Fossati', playingStyle: '4-3-3', keyPlayers: ['Gianluca Lapadula', 'Renato Tapia', 'André Carrillo'], strengths: ['Passionate fanbase', 'Tactical discipline', 'Tournament experience'], weaknesses: ['Ageing squad', 'Goalscoring concerns'], groupOpponents: ['Italy', 'Iran', 'Cameroon'], overview: 'Peru return to the World Cup stage carried by one of the most passionate fan bases in South American football. La Blanquirroja were surprise quarter-finalists in the 1970s and rebuilt their reputation with a spirited 2018 campaign. Their fans alone make them one of the tournament\'s most colourful participants.', tacticalAnalysis: 'Peru play a patient, possession-based 4-3-3 that relies on midfield control and intelligent movement. Tapia anchors the midfield, allowing the more creative players ahead of him to find pockets of space. Peru\'s greatest strength is their collective understanding and willingness to play for each other.' },
};

// Generate basic data for teams without detailed profiles
function getDefaultTeamData(code: string, name: string, flag: string, group: string): WCTeamData {
  return {
    name, code, flag, group,
    confederation: 'N/A', fifaRanking: 0, wcAppearances: 0,
    bestFinish: 'N/A', manager: 'TBC', playingStyle: 'TBC',
    keyPlayers: [], strengths: [], weaknesses: [],
    groupOpponents: [],
    overview: `${name} have qualified for the 2026 FIFA World Cup and will compete in Group ${group}. They will be looking to make an impact on the world stage and progress through the group phase.`,
    tacticalAnalysis: `Full tactical analysis for ${name} will be available closer to the tournament kickoff.`,
  };
}

// Groups data (same as WorldCup.tsx)
const GROUPS: Record<string, { name: string; code: string; flag: string }[]> = {
  A: [{ name: 'Mexico', code: 'MEX', flag: '🇲🇽' }, { name: 'South Korea', code: 'KOR', flag: '🇰🇷' }, { name: 'Czechia', code: 'CZE', flag: '🇨🇿' }, { name: 'South Africa', code: 'RSA', flag: '🇿🇦' }],
  B: [{ name: 'Canada', code: 'CAN', flag: '🇨🇦' }, { name: 'Australia', code: 'AUS', flag: '🇦🇺' }, { name: 'Bosnia & Herz.', code: 'BIH', flag: '🇧🇦' }, { name: 'Qatar', code: 'QAT', flag: '🇶🇦' }],
  C: [{ name: 'Brazil', code: 'BRA', flag: '🇧🇷' }, { name: 'Morocco', code: 'MAR', flag: '🇲🇦' }, { name: 'Scotland', code: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' }, { name: 'Haiti', code: 'HAI', flag: '🇭🇹' }],
  D: [{ name: 'USA', code: 'USA', flag: '🇺🇸' }, { name: 'Turkey', code: 'TUR', flag: '🇹🇷' }, { name: 'Paraguay', code: 'PAR', flag: '🇵🇾' }, { name: 'Croatia', code: 'CRO', flag: '🇭🇷' }],
  E: [{ name: 'Germany', code: 'GER', flag: '🇩🇪' }, { name: 'Ivory Coast', code: 'CIV', flag: '🇨🇮' }, { name: 'Curaçao', code: 'CUW', flag: '🇨🇼' }, { name: 'Ecuador', code: 'ECU', flag: '🇪🇨' }],
  F: [{ name: 'Netherlands', code: 'NED', flag: '🇳🇱' }, { name: 'Japan', code: 'JPN', flag: '🇯🇵' }, { name: 'Sweden', code: 'SWE', flag: '🇸🇪' }, { name: 'Tunisia', code: 'TUN', flag: '🇹🇳' }],
  G: [{ name: 'Argentina', code: 'ARG', flag: '🇦🇷' }, { name: 'Colombia', code: 'COL', flag: '🇨🇴' }, { name: 'Austria', code: 'AUT', flag: '🇦🇹' }, { name: 'Uzbekistan', code: 'UZB', flag: '🇺🇿' }],
  H: [{ name: 'Spain', code: 'ESP', flag: '🇪🇸' }, { name: 'Saudi Arabia', code: 'KSA', flag: '🇸🇦' }, { name: 'Cape Verde', code: 'CPV', flag: '🇨🇻' }, { name: 'Jordan', code: 'JOR', flag: '🇯🇴' }],
  I: [{ name: 'France', code: 'FRA', flag: '🇫🇷' }, { name: 'Senegal', code: 'SEN', flag: '🇸🇳' }, { name: 'Norway', code: 'NOR', flag: '🇳🇴' }, { name: 'Iraq', code: 'IRQ', flag: '🇮🇶' }],
  J: [{ name: 'England', code: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' }, { name: 'Ghana', code: 'GHA', flag: '🇬🇭' }, { name: 'Panama', code: 'PAN', flag: '🇵🇦' }, { name: 'Algeria', code: 'ALG', flag: '🇩🇿' }],
  K: [{ name: 'Portugal', code: 'POR', flag: '🇵🇹' }, { name: 'DR Congo', code: 'COD', flag: '🇨🇩' }, { name: 'Nigeria', code: 'NGA', flag: '🇳🇬' }, { name: 'Switzerland', code: 'SUI', flag: '🇨🇭' }],
  L: [{ name: 'Italy', code: 'ITA', flag: '🇮🇹' }, { name: 'Iran', code: 'IRN', flag: '🇮🇷' }, { name: 'Cameroon', code: 'CMR', flag: '🇨🇲' }, { name: 'Peru', code: 'PER', flag: '🇵🇪' }],
};

export default function WCTeamPage() {
  const { code } = useParams<{ code: string }>();
  const upperCode = code?.toUpperCase() || '';

  // Find team in groups
  let teamInfo: { name: string; code: string; flag: string } | null = null;
  let groupName = '';
  for (const [g, teams] of Object.entries(GROUPS)) {
    const found = teams.find(t => t.code === upperCode);
    if (found) { teamInfo = found; groupName = g; break; }
  }

  if (!teamInfo) {
    return (
      <div className="min-h-screen bg-background">
        <Header />
        <div className="container text-center py-20">
          <p className="text-lg font-medium text-muted-foreground">Team not found</p>
          <Link to="/worldcup" className="text-primary hover:underline text-sm mt-2 inline-block">← Back to World Cup</Link>
        </div>
      </div>
    );
  }

  const data = TEAM_DATA[upperCode] || getDefaultTeamData(upperCode, teamInfo.name, teamInfo.flag, groupName);
  const groupTeams = GROUPS[groupName] || [];

  return (
    <div className="min-h-screen bg-background">
      <SEOHead
        title={`${teamInfo.name} — World Cup 2026 Squad, Group, Key Players & Analysis | LastFootball`}
        description={`${teamInfo.name} at the 2026 FIFA World Cup: Group ${groupName} draw, squad, key players, tactical analysis, and tournament history. ${data.manager ? `Manager: ${data.manager}.` : ''} ${data.keyPlayers.length ? `Key players: ${data.keyPlayers.join(', ')}.` : ''}`}
        path={`/worldcup/team/${code}`}
      />
      <Header />

      {/* Hero */}
      <section className="bg-gradient-to-b from-[#1a0a2e] via-[#0d1a3a] to-background border-b border-amber-500/20">
        <div className="container max-w-4xl py-8">
          <Link to="/worldcup" className="inline-flex items-center gap-1 text-xs text-amber-400/60 hover:text-amber-400 mb-4 transition-colors">
            <ArrowLeft className="w-3.5 h-3.5" /> World Cup 2026
          </Link>

          <div className="flex items-center gap-5">
            <Flag code={teamInfo.code} size={72} className="rounded" />
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="text-[10px] font-bold bg-amber-500/20 text-amber-400 px-2 py-0.5 rounded-full uppercase">Group {groupName}</span>
                {data.fifaRanking > 0 && (
                  <span className="text-[10px] font-bold bg-white/10 text-white/70 px-2 py-0.5 rounded-full">FIFA #{data.fifaRanking}</span>
                )}
              </div>
              <h1 className="text-3xl sm:text-4xl font-black text-white">{teamInfo.name}</h1>
              {data.manager && data.manager !== 'TBC' && (
                <p className="text-sm text-white/50 mt-1">Manager: {data.manager} · {data.playingStyle}</p>
              )}
            </div>
          </div>

          {/* Quick facts */}
          {data.wcAppearances > 0 && (
            <div className="grid grid-cols-3 gap-3 mt-5">
              <div className="bg-white/5 rounded-lg p-3 text-center border border-white/10">
                <p className="text-xl font-black text-amber-400">{data.wcAppearances}</p>
                <p className="text-[10px] text-white/50 uppercase">WC Appearances</p>
              </div>
              <div className="bg-white/5 rounded-lg p-3 text-center border border-white/10">
                <p className="text-sm font-bold text-amber-400">{data.bestFinish}</p>
                <p className="text-[10px] text-white/50 uppercase">Best Finish</p>
              </div>
              <div className="bg-white/5 rounded-lg p-3 text-center border border-white/10">
                <p className="text-sm font-bold text-amber-400">{data.confederation}</p>
                <p className="text-[10px] text-white/50 uppercase">Confederation</p>
              </div>
            </div>
          )}
        </div>
      </section>

      <main className="container max-w-4xl py-6 pb-20 md:pb-6 space-y-5">
        {/* Overview */}
        <section className="bg-card border border-border rounded-xl p-5">
          <h2 className="text-sm font-bold text-foreground mb-3 flex items-center gap-2">
            <Trophy className="w-4 h-4 text-amber-400" /> {teamInfo.name} at the 2026 World Cup
          </h2>
          <p className="text-sm text-foreground/80 leading-relaxed">{data.overview}</p>
        </section>

        {/* Group */}
        <section className="bg-card border border-border rounded-xl p-5">
          <h2 className="text-sm font-bold text-foreground mb-3 flex items-center gap-2">
            <Users className="w-4 h-4 text-amber-400" /> Group {groupName}
          </h2>
          <div className="space-y-2">
            {groupTeams.map(t => (
              <Link
                key={t.code}
                to={`/worldcup/team/${t.code.toLowerCase()}`}
                className={cn(
                  'flex items-center gap-3 px-3 py-2.5 rounded-lg transition-colors',
                  t.code === upperCode ? 'bg-amber-500/10 border border-amber-500/20' : 'hover:bg-secondary/30',
                )}
              >
                <Flag code={t.code} size={24} />
                <span className={cn('text-sm font-medium', t.code === upperCode ? 'text-amber-400 font-bold' : 'text-foreground')}>{t.name}</span>
                {t.code === upperCode && <span className="text-[9px] bg-amber-500/20 text-amber-400 px-1.5 py-0.5 rounded font-bold ml-auto">YOU ARE HERE</span>}
              </Link>
            ))}
          </div>
        </section>

        {/* Key Players */}
        {data.keyPlayers.length > 0 && (
          <section className="bg-card border border-border rounded-xl p-5">
            <h2 className="text-sm font-bold text-foreground mb-3 flex items-center gap-2">
              <Star className="w-4 h-4 text-amber-400" /> Key Players
            </h2>
            <div className="space-y-2">
              {data.keyPlayers.map(p => (
                <div key={p} className="flex items-center gap-2 px-2 py-1.5">
                  <span className="text-primary">⚽</span>
                  <span className="text-sm font-medium text-foreground">{p}</span>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Tactical Analysis */}
        {data.tacticalAnalysis && data.tacticalAnalysis !== `Full tactical analysis for ${teamInfo.name} will be available closer to the tournament kickoff.` && (
          <section className="bg-card border border-border rounded-xl p-5">
            <h2 className="text-sm font-bold text-foreground mb-3">Tactical Blueprint</h2>
            <p className="text-sm text-foreground/80 leading-relaxed">{data.tacticalAnalysis}</p>
          </section>
        )}

        {/* Strengths & Weaknesses */}
        {(data.strengths.length > 0 || data.weaknesses.length > 0) && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {data.strengths.length > 0 && (
              <section className="bg-card border border-emerald-500/20 rounded-xl p-4">
                <h3 className="text-xs font-bold text-emerald-400 uppercase tracking-wider mb-2">Strengths</h3>
                {data.strengths.map(s => (
                  <p key={s} className="text-sm text-foreground/80 py-1 flex items-start gap-2">
                    <span className="text-emerald-400 mt-0.5">✓</span> {s}
                  </p>
                ))}
              </section>
            )}
            {data.weaknesses.length > 0 && (
              <section className="bg-card border border-red-500/20 rounded-xl p-4">
                <h3 className="text-xs font-bold text-red-400 uppercase tracking-wider mb-2">Weaknesses</h3>
                {data.weaknesses.map(w => (
                  <p key={w} className="text-sm text-foreground/80 py-1 flex items-start gap-2">
                    <span className="text-red-400 mt-0.5">✗</span> {w}
                  </p>
                ))}
              </section>
            )}
          </div>
        )}

        {/* SEO FAQ */}
        <section className="bg-card border border-border rounded-xl overflow-hidden">
          <div className="px-4 py-3 border-b border-border/30">
            <h2 className="text-sm font-bold text-foreground">People Also Ask about {teamInfo.name}</h2>
          </div>
          <WCTeamFaq name={teamInfo.name} data={data} group={groupName} />
        </section>

        {/* Back to WC */}
        <Link to="/worldcup" className="flex items-center justify-center gap-2 py-3 text-sm text-amber-400 font-semibold hover:text-amber-300 transition-colors">
          ← Back to World Cup 2026 Hub
        </Link>
      </main>
    </div>
  );
}

function WCTeamFaq({ name, data, group }: { name: string; data: WCTeamData; group: string }) {
  const [openIdx, setOpenIdx] = useState<number | null>(null);

  const faqs = [
    { q: `What group is ${name} in at the 2026 World Cup?`, a: `${name} have been drawn in Group ${group} for the 2026 FIFA World Cup, alongside ${data.groupOpponents.length ? data.groupOpponents.join(', ') : 'their group opponents'}.` },
    { q: `Who is the manager of ${name}?`, a: data.manager !== 'TBC' ? `${name} are managed by ${data.manager}, who deploys a ${data.playingStyle} formation.` : `The manager of ${name} for the 2026 World Cup is to be confirmed.` },
    { q: `How many World Cups has ${name} played in?`, a: data.wcAppearances > 0 ? `${name} have appeared in ${data.wcAppearances} FIFA World Cup tournaments. Their best finish was ${data.bestFinish}.` : `${name}'s World Cup history details will be updated soon.` },
    { q: `Who are ${name}'s key players for the 2026 World Cup?`, a: data.keyPlayers.length ? `${name}'s key players for the 2026 World Cup include ${data.keyPlayers.join(', ')}. These players will be crucial to their tournament hopes.` : `${name}'s key players for the 2026 World Cup will be confirmed in the squad announcement.` },
    { q: `When do ${name} play their first World Cup 2026 match?`, a: `${name}'s Group ${group} fixtures in the 2026 FIFA World Cup will begin in the group stage starting June 11, 2026. The full schedule with dates and venues will be available on LastFootball.` },
  ];

  return (
    <div className="divide-y divide-border/10">
      {faqs.map((faq, i) => (
        <button key={i} onClick={() => setOpenIdx(openIdx === i ? null : i)} className="w-full text-left px-4 py-3 hover:bg-secondary/20 transition-colors">
          <div className="flex items-center justify-between gap-2">
            <span className="text-sm font-semibold text-foreground">{faq.q}</span>
            <ChevronRight className={cn('w-4 h-4 text-muted-foreground flex-shrink-0 transition-transform', openIdx === i && 'rotate-90')} />
          </div>
          {openIdx === i && <p className="text-sm text-foreground/75 leading-relaxed mt-2 pr-6">{faq.a}</p>}
        </button>
      ))}
    </div>
  );
}
