// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database as GeneratedDatabase } from './types';
import type { ExtraTables } from './types-extra';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Merge the auto-generated schema with the supplementary tables (types-extra.ts)
// that weren't present in the generated file, so all tables are fully typed.
type PublicSchema = GeneratedDatabase['public'];
type MergedDatabase = Omit<GeneratedDatabase, 'public'> & {
  public: Omit<PublicSchema, 'Tables'> & {
    Tables: PublicSchema['Tables'] & ExtraTables;
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<MergedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: async (_name, _acquireTimeout, fn) => await fn(),
  }
});
